### ISSUE TITLE
Sending Emails to Content Lists function future?

### ISSUE THREAD

**Issue by swacsa** [SenseNet/sn-workflow#7]
Hi!

I've found that the "Sending Emails to Content Lists" function is missing now from the SN7 modules, I can't see it in the ZenHub board neither: http://wiki.sensenet.com/Sending_Emails_to_Content_Lists

My goal is to upload contents (articles) which are written in an email client (for example using Outlook) to the portal, and after I can handle them (search, list, etc...)

Is it out of your scope or you will schedule in your roadmap?

**Comment by tusmester** [comment]
The feature is actually there and it should be working. What is _not there_ is the link on the main Settings page, because it would be too complicated to add the link to that html view when installing the workflow component.

I think the simplest solution would be to add the **Incoming email settings** action to the **Settings scenario** so that it appears in the Settings menu on the top right corner in lists.

**Comment by swacsa** [comment]
Thanks, I see this function, I'll try it!
